### PR TITLE
Bug fix: Mail Child domain A record and MX record

### PR DESCRIPTION
**Pull request by istiak101**
Previously it would create mail.mail.example.com records. Now mail.example.com

### CODE REVIEW

**Comment by usmannasir** [comment]
This will create issues if the user only creates a subdomain on CyberPanel as you have used `topLevelDomain` variable. I will try to take care of this some other way.

thanks.

**Comment by istiak101** [comment]
Aren't these records specific to mail subdomain? Also I tested locally. Looks good to me.

**Comment by istiak101** [comment]
Understood. Tested that too. mail.mail.subdomain.example.com previously. Now mail.subdomain.example.com

And you are right probably. If this is merged there is no need to create Mail A record for `topLevelDomain`  because that is already created if you provide a top level domain. But for sub-domain you need to create that Mail A record.

**Comment by istiak101** [comment]
Yes, this solution was incorrect. Will you please take a look at this one?
https://github.com/istiak101/cyberpanel/commit/a0f2cf9e870c76fc7368286ad2957568b39518b7#diff-8e80ce10f2ad16ff76973b5388eb1096

**Comment by usmannasir** [comment]
How about this -> https://github.com/usmannasir/cyberpanel/commit/0774ffea96c9e27e4d2f55bcbbc777ac01307b6d

**Comment by istiak101** [comment]
Yep, works good. What about MX? It also need this check.

**Pull request closed without merging**
